server {
    listen 8080;
    server_name my_webserv;
    client_max_body_size 10M;

    error_page 404 /404.html;

    location / {
        root /home/mavissar/Desktop/Webserv/www;
        index index.html;
        allow_methods GET;
        autoindex off;
    }
}